# Generated by Django 4.0.4 on 2022-05-29 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='loguser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=32, verbose_name='登录账号')),
                ('password', models.CharField(max_length=20, verbose_name='密码')),
            ],
        ),
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='姓名')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('gender', models.CharField(choices=[('1', '男'), ('2', '女')], max_length=1, verbose_name='性别')),
                ('head_img', models.ImageField(blank=True, null=True, upload_to='headimage', verbose_name='头像')),
                ('attachment', models.FileField(blank=True, null=True, upload_to='filedir', verbose_name='附件')),
            ],
        ),
    ]
