# Generated by Django 4.0.4 on 2022-05-29 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dep_name', models.CharField(max_length=32, unique=True, verbose_name='部门名称')),
                ('dep_script', models.CharField(max_length=60, null=True, verbose_name='备注')),
            ],
        ),
        migrations.CreateModel(
            name='loguser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account', models.CharField(max_length=32, verbose_name='用户名')),
                ('password', models.CharField(max_length=32, verbose_name='密码')),
            ],
        ),
        migrations.CreateModel(
            name='person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='部门名称')),
                ('email', models.EmailField(max_length=254, verbose_name='邮箱')),
                ('gender', models.IntegerField(verbose_name='性别')),
                ('head_img', models.ImageField(upload_to='test_view_pic')),
            ],
        ),
    ]
